// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjuarcwrrthygxlrrckq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdWFyY3dycnRoeWd4bHJyY2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODk3MjIsImV4cCI6MjA2NDg2NTcyMn0.gDBin1pJ0uu-VVFmlcT95df5N5pGQSoXkw9EvRG8Xy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);